### ISSUE TITLE
Scripts used to combine/filter the tables

### ISSUE THREAD

**Issue by zhaofengli** [jasonqng/chinese-keywords#2]
Could you open-source the scripts used to combine the sub-tables? I'd like to help add notes and translations, but find the files difficult to work on. Also, UTF-8 may be a better choice for the project, with better support across platforms.

**Comment by jasonqng** [comment]
At the moment, new sub-tables are just merged into a single Stata dataset I have, and then I export out from it the final CSV files uploaded here. Indeed, would be great if you could add notes and more translations. What do you suggest would be the best way to do it if editing these CSV files directly is difficult?

The three CSV files in /csv are in UTF-8, it's the files in csv/individual that are gb2312.

**Comment by zhaofengli** [comment]
Thanks for the response. I'd suggest making the Stata dataset public, then.

**Comment by jasonqng** [comment]
Sounds good. I've posted to /dta
